### ISSUE TITLE
issue/pr/work rollup allow for 'ignore these repos by prefix'

### ISSUE THREAD

**Issue by hanbollar** [KittyCAD/ts-actions#129]
we have some repos whose changes/work we dont want added to the update/sync rollup

these repos are pre-pended by '_' just to denote theyre 'privateprivate'

we use these repos for hr purposes which is why theyre required to be private to the company and not just to outside users

could there be a param or something added to the workflow action so that we can ignore all user interactions in repos that start with '_'

i manually deleted the written items from the generated .md for this week's one

(not sure if this is the right place or if this is meant for the Eng repo specifically, so feel free to move the issue as needed)

**Comment by Irev-Dev** [comment]
Oh yup, that should be a quick fix.

**Comment by Irev-Dev** [comment]
Resolved by https://github.com/KittyCAD/ts-actions/pull/134
